export const importMap = {
    '/ConsultanExpert/talkToLawyer': () => import('../pages/ConsultanExpert/talkToLawyer.jsx'),
    '/ConsultanExpert/talkToCA': () => import('../pages/ConsultanExpert/talkToCA.jsx'),
    '/ConsultanExpert/talkToCS': () => import('../pages/ConsultanExpert/talkToCS.jsx'),
    '/ConsultanExpert/talkToIP': () => import('../pages/ConsultanExpert/talkToIP.jsx'),

    '/BusinessSetup/plc': () => import('../pages/BusinessSetup/plc.jsx'),
    '/BusinessSetup/llp': () => import('../pages/BusinessSetup/llp.jsx'),
    '/BusinessSetup/opc': () => import('../pages/BusinessSetup/opc.jsx'),
    '/BusinessSetup/sp': () => import('../pages/BusinessSetup/sp.jsx'),
    '/BusinessSetup/nidhi': () => import('../pages/BusinessSetup/nidhi.jsx'),
    '/BusinessSetup/producer': () => import('../pages/BusinessSetup/producer.jsx'),
    '/BusinessSetup/partnership': () => import('../pages/BusinessSetup/partnership.jsx'),
    '/BusinessSetup/startup': () => import('../pages/BusinessSetup/startup.jsx'),

    '/International/us': () => import('../pages/International/us.jsx'),
    '/International/singapore': () => import('../pages/International/singapore.jsx'),
    '/International/uk': () => import('../pages/International/uk.jsx'),
    '/International/netherlands': () => import('../pages/International/netherlands.jsx'),
    '/International/hong-kong': () => import('../pages/International/hong-kong.jsx'),
    '/International/dubai': () => import('../pages/International/dubai.jsx'),
    '/International/international-trademark': () => import('../pages/International/international-trademark.jsx'),

    '/Licenses/dsc': () => import('../pages/Licenses/dsc.jsx'),
    '/Licenses/udyam': () => import('../pages/Licenses/udyam.jsx'),
    '/Licenses/msme': () => import('../pages/Licenses/msme.jsx'),
    '/Licenses/iso': () => import('../pages/Licenses/iso.jsx'),
    '/Licenses/fssai': () => import('../pages/Licenses/fssai.jsx'),
    '/Licenses/iec': () => import('../pages/Licenses/iec.jsx'),
    '/Licenses/spice-board': () => import('../pages/Licenses/spice-board.jsx'),
    '/Licenses/fieo': () => import('../pages/Licenses/fieo.jsx'),
    '/Licenses/legal-metrology': () => import('../pages/Licenses/legal-metrology.jsx'),
    '/Licenses/hallmark': () => import('../pages/Licenses/hallmark.jsx'),
    '/Licenses/bis': () => import('../pages/Licenses/bis.jsx'),
    '/Licenses/liquor': () => import('../pages/Licenses/liquor-license.jsx'),
    '/Licenses/clra': () => import('../pages/Licenses/clra.jsx'),
    '/Licenses/adcode': () => import('../pages/Licenses/ad-code.jsx'),
    '/Licenses/irdai': () => import('../pages/Licenses/irdai.jsx'),
    '/Licenses/drug-cosmetic': () => import('../pages/Licenses/drug-cosmetic.jsx'),
    '/Licenses/apeda-rcmc': () => import('../pages/Licenses/APEDARegistrationPage.jsx'),
    '/Licenses/customs-clearance': () => import('../pages/Licenses/CustomsClearancePage.jsx'),

    '/Fundraising': () => import('../pages/Fundraising/index.jsx'),
    '/Fundraising/pitch-deck': () => import('../pages/Fundraising/pitch-deck.jsx'),
    '/Fundraising/business-loan': () => import('../pages/Fundraising/business-loan.jsx'),
    '/Fundraising/dpr': () => import('../pages/Fundraising/dpr.jsx'),

    '/NGO': () => import('../pages/NGO/index.jsx'),
    '/NGO/section-8': () => import('../pages/NGO/section-8.jsx'),
    '/NGO/trust': () => import('../pages/NGO/trust.jsx'),
    '/NGO/society': () => import('../pages/NGO/society.jsx'),
    '/NGO/compliance': () => import('../pages/NGO/compliance.jsx'),
    '/NGO/section8': () => import('../pages/NGO/compliance-section-8.jsx'),
    '/NGO/csr1': () => import('../pages/NGO/csr1.jsx'),
    '/NGO/80g-12a': () => import('../pages/NGO/80g-12a.jsx'),
    '/NGO/darpan': () => import('../pages/NGO/darpan.jsx'),
    '/NGO/fcra': () => import('../pages/NGO/fcra.jsx'),
};
