spring.datasource.url=jdbc:mysql://localhost:3306/velmess_billing?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=hado
# USER: PLEASE SET YOUR MYSQL PASSWORD BELOW
spring.datasource.password=Hadoglobal@123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8085
